### PR TITLE
add error handling to selendroid install for older npm systems

### PR DESCRIPTION
**Pull request by jlipps**

### CODE REVIEW

**Comment by imurchie** [comment]
Ugh. But ok.

We really ought to rethink this npm install script strategy.

**Comment by jlipps** [comment]
Indeed. I think the hooks are better in npm v3, which we should require as soon as reasonably possible

**Comment by jlipps** [comment]
published as 1.2.2

**Comment by imurchie** [comment]
Yes indeed. Plus things are flattened, which cleans up a lot of the logic. This error appears to be long-standing (3+ years).

**Pull request merged**
