### PR TITLE
Set the default context when we create a session

### PR DESCRIPTION
**Pull request by scottdixon**
Resolves https://github.com/appium/appium/issues/6234

@imurchie

### CODE REVIEW

**Comment by imurchie** [comment]
I guess this depends on how we interpret the specification. 

```
GET /session/:sessionid/context
  returns one of:
    a string representing the current context
    `null`, representing "no context"
```

**Comment by scottdixon** [comment]
Some interesting findings:

#### Android Driver 
Immediately sets context to `NATIVE_APP` (both 1.4 & 1.5):
- 1.4: https://github.com/appium/appium-android-driver/blob/master/lib/driver.js#L93
- 1.5: https://github.com/appium/appium/blob/1.4/lib/devices/android/android.js#L58

#### iOS Driver 
Sets context to `null` initially (both 1.4 & 1.5)
- https://github.com/appium/appium-ios-driver/blob/master/lib/driver.js#L55
- https://github.com/appium/appium/blob/1.4/lib/devices/ios/ios.js#L105

but will [always return `NATIVE_APP` in lieu of `null`](https://github.com/appium/appium-ios-driver/blob/de679870ee1c44da8771fde0657681a5c04ebe20/lib/commands/context.js#L17-L23) (1.4 exhibits this behavior too)

#### Selendroid Driver
sets to `NATIVE_APP` (1.4) and `null` (1.5):
- https://github.com/appium/appium/blob/1.4/lib/devices/android/selendroid.js#L75

---
Reading the spec, I appears it's implemented incorrectly across all devices. However, the current logic might make sense because you're always either in a native or web context (at least on said devices), right? With autoLaunch gone, is there any way to be in "no context"?

**Comment by imurchie** [comment]
I agree, we are always in a context, so the default should be NATIVE_APP. Feel free to merge.

**Comment by scottdixon** [comment]
Published as v1.3.3

**Pull request merged**
