### PR TITLE
Update network connection state change in Selendroid driver

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Fixes the same problem as in https://github.com/appium/appium-uiautomator2-driver/pull/68

### CODE REVIEW

**Comment by jlipps** [comment]
@mykola-mokhnach you're the maintainer of this project now, so merge at will :-)

**Comment by mykola-mokhnach** [comment]
@jlipps should I also increase component version number every time I merge something new?

**Comment by mykola-mokhnach** [comment]
screen

**Comment by imurchie** [comment]
@mykola-mokhnach Do you mean in `package.json`? Then no. That gets updated through publishing.

The process is:
1. merge PR
2. Pull master locally
3. `npm version [major|minor|patch]` (which one depends on what sort of changes they are)
4. git push --tags origin master
5. `npm publish`

Step `3` will update the `package.json` version number and create a tag in git.

**Comment by mykola-mokhnach** [comment]
How can I merge to master if I don't have write access to the repository?

**Comment by imurchie** [comment]
Do you not? I thought that's what @jlipps was talking about.

**Comment by jlipps** [comment]
ok @mykola-mokhnach i gave you owner rights over the whole appium org. use this awesome power with care :-)

**Comment by mykola-mokhnach** [comment]
hqdefault

**Comment by jlipps** [comment]
also, I always add a step in between isaac's (2) and (3):

2b: `rm -rf node_modules && npm install`, and rerun unit tests

just as a safety mechanism before publishing, to ensure that i'm getting all the latest deps that a new install would get.

**Pull request merged**
